### ISSUE TITLE
Wondering why best STEP and LAYER parameter differs between real images

### ISSUE THREAD

**Issue by JinwooMcLee** [TencentARC/MasaCtrl#30]
First of all, thank you for sharing great research! It's really inspiring.

I've been gone through the code and make tweaks and tested it with real images. Now I have two questions.

1. For real image editing (with or without t2i adapter), some images require less STEP, LAYER for MasaAttention, some requires more, and a few images cannot be generated correctly.

Maybe model knows some object really well (i.e. human) on its diverse settings, therefore it works well?

Especially, I'm wondering how can I improve on the real images that MasaCtrl doesn't work.

2. Using intermediate ref_latents works great. Could you refer me a paper that suggested this approach? I want to dig into it more.

Again, thank you for amazing work ☺️

**Comment by ljzycmd** [comment]
Hi @JinwooMcLee, 

1. As for the step and layer control strategy hyperparameters, we found current STEP and LAYER can achieve better results than other control steps and layers in most cases.  You may adjust them slightly around the current STEP and LAYER to obtain the best editing results. Note that when editing with controllable diffusion models (T2I-Adapter, ControlNet), you may adjust the control steps and layers smaller,  since additional controls can faithfully guide the target layout.  
2. As for the failure during real image editing, the noise obtained by DDIM inversion cannot reconstruct the source image faithfully in some cases, leading to an editing failure accordingly. Therefore, we try to alleviate this problem by directly querying the intermediate features (obtained from the DDIM inversion rather than the synthesis process). This operation is inspired by the previous Null-text Inversion [1], but we don't optimize the null text embedding. You may also try these improved diffusion-based inversion techniques [1, 2, 3] for better performance.

Related links:
[1] [Null-text Inversion for Editing Real Images using Guided Diffusion Models](https://arxiv.org/abs/2211.09794)
[2] [Negative-prompt Inversion: Fast Image Inversion for Editing with Text-guided Diffusion Models](https://arxiv.org/abs/2305.16807)
[3] [Improving Tuning-Free Real Image Editing via Proximal Guidance](https://arxiv.org/abs/2306.05414)

**Comment by JinwooMcLee** [comment]
@ljzycmd 
Thank you for detailed and clear explanation!
