### ISSUE TITLE
Different Results

### ISSUE THREAD

**Issue by kingnobro** [TencentARC/MasaCtrl#32]
Thanks for your code; it's really helpful. I downloaded the source code and ran the `playground_real.ipynb`. The only modification is that I use `latents_list`:
```python
image_masactrl = model(prompts,
  latents=start_code,
  guidance_scale=7.5,
  ref_intermediate_latents=latents_list)
```
Here is the generated image. The corgi's leg is not as perfect as shown in the `README`.
![image](https://github.com/TencentARC/MasaCtrl/assets/43701476/7c1c2998-8509-494d-af1d-b225f97c6c3c)

I am trying to figure out what's going wrong. Do you have any idea? Thank you.

**Comment by ljzycmd** [comment]
Hi @kingnobro, thanks for your interest. 

1. When the noise map inverted with DDIM cannot reconstruct the source image, querying the intermediate latents during DDIM inversion processing can alleviate this problem significantly. Since MasaCtrl performs editing based on the feature similarity across source and target images, the fractional editing results would occur due to the inaccurate feature correspondence built with mutual self-attention.

2. Since MasaCtrl tries to combine the contents of the source image and the layout of the target image to generate the desired image, it would fail when the target prompt cannot synthesize the target image layout. As a result, recent controllable diffusion models like T2I-Adapter and ControlNet can generate an image with the desired layout, thus we can integrate MasaCtrl to them to edit images more faithfully. Meanwhile, for the cartoon image synthesis and editing, you may try the anime-style checkpoint Anything-V4.

**Comment by kingnobro** [comment]
Thanks lot!
