### ISSUE TITLE
Why Does It Succeed on SD v1-4 but Fail on SD v1-5?

### ISSUE THREAD

**Issue by x2x5** [TencentARC/MasaCtrl#51]
All code remains the same except for the SD version.

**v1-4:**

![image](https://github.com/user-attachments/assets/e8aa77bd-3f1e-44fc-ae3f-7a10d376997e)

**v1-5:**

![image](https://github.com/user-attachments/assets/5eede9ef-8e25-47a1-bcff-0428f3b3554f)

Initially, I was using v1-5 but found it too difficult to reproduce the results. So, I tried redownloading the code and running the original version without any changes. To my surprise, the SD version had a significant impact: the method worked successfully on v1-4 but failed on v1-5. I’m unsure how to interpret this. Does it mean that this method only works with the v1-4 SD version?

**Comment by ljzycmd** [comment]
Hi @tian-2024, thanks for your interest. **The failure is caused by the inaccurate DDIM inversion**, where the inverted noise map cannot reconstruct the input image, as shown in the second column in your figure. To alleviate this, you can 1) increase the inversion steps to obtain a more accurate inverted noise map, and 2) use the intermediate features during the inversion process for the editing (as indicated in the notebook demo). 

Hope the above can help you.

**Comment by x2x5** [comment]
> Hi @tian-2024, thanks for your interest. **The failure is caused by the inaccurate DDIM inversion**, where the inverted noise map cannot reconstruct the input image, as shown in the second column in your figure. To alleviate this, you can 1) increase the inversion steps to obtain a more accurate inverted noise map, and 2) use the intermediate features during the inversion process for the editing (as indicated in the notebook demo).
> 
> Hope the above can help you.

![image](https://github.com/user-attachments/assets/2dfc6aa9-0300-4f9b-919f-76c167845977)

Thank you for your so quick feedback~ I tried playground now, and it became better before~

So it's the problem of inaccurate ddim inversion.
